## Imports

In [1]:
import pandas as pd
import numpy as np 

pd.set_option('display.max_rows',100)
pd.set_option('display.max_columns',150)

In [2]:
## Importing dataset

In [4]:
df = pd.read_pickle('../data/lgd_ead_expected_loss_output.pkl')
print(df.shape)

df[[ "actual_default_flag", "pd_score", "lgd_estimate", "ead", "expected_loss", "risk_adjusted_return", "risk_band", "risk_score"]].head()

(40000, 150)

,actual_default_flag,pd_score,lgd_estimate,ead,expected_loss,risk_adjusted_return,risk_band,risk_score
0,1,0.495415,12972.271803,12000,7.711987e+07,-7.711748e+07,High,505.0
1,0,0.504460,9378.598331,20100,9.509568e+07,-9.509254e+07,High,496.0
2,0,0.301881,7761.744126,8000,1.874498e+07,-1.874409e+07,Low,698.0
3,0,0.685799,9378.598331,23325,1.500226e+08,-1.500196e+08,Very High,314.0
4,0,0.739917,13736.755080,21250,2.159862e+08,-2.159813e+08,Very High,260.0

## Check Key Risk Metrics

In [5]:
df[["pd_score", "lgd_estimate", "ead", "expected_loss", "risk_adjusted_return", "risk_band", "risk_score"]].describe()

,pd_score,lgd_estimate,ead,expected_loss,risk_adjusted_return,risk_score
count,40000.000000,40000.000000,40000.000000,4.000000e+04,4.000000e+04,40000.000000
mean,0.438078,9132.302467,14513.557500,6.693773e+07,-6.693572e+07,561.922650
std,0.215661,1894.923989,8711.779018,6.916339e+07,6.916191e+07,215.661473
min,0.025880,7011.446304,500.000000,4.436265e+05,-5.155464e+08,32.000000
25%,0.263283,7761.744126,8000.000000,1.872799e+07,-9.190398e+07,402.000000
50%,0.421281,9378.598331,12000.000000,4.117028e+07,-4.116852e+07,579.000000
75%,0.598333,10760.132439,20000.000000,9.190598e+07,-1.872715e+07,737.000000
max,0.967616,15456.646328,40000.000000,5.155572e+08,-4.435292e+05,974.000000

In [16]:
df[['expected_loss','risk_adjusted_return']].describe()

       expected_loss  risk_adjusted_return
count   4.000000e+04          4.000000e+04
mean    6.693773e+07         -6.693572e+07
std     6.916339e+07          6.916191e+07
min     4.436265e+05         -5.155464e+08
25%     1.872799e+07         -9.190398e+07
50%     4.117028e+07         -4.116852e+07
75%     9.190598e+07         -1.872715e+07
max     5.155572e+08         -4.435292e+05

In [17]:
df['risk_band'].unique()

['High', 'Low', 'Very High', 'Medium', 'Very Low']
Categories (5, object): ['Very Low' < 'Low' < 'Medium' < 'High' < 'Very High']

## Create Loan Decision Rule

In [18]:
def loan_decision(row):
    if (row['risk_band'] in ['Very Low', 'Low'] and row['expected_loss'] <= 20000000 and row['risk_adjusted_return']>0):
        return 'Approve'
    elif (row['risk_band']== 'Medium' and row['expected_loss'] <= 50000000):
        return 'Manual Review'
    else:
        return 'Reject'

## Apply Decision Rules

In [19]:
df['loan_decision']=df.apply(loan_decision, axis=1)
df['loan_decision'].value_counts()

loan_decision
Reject           35298
Manual Review     4702
Name: count, dtype: int64